[package]
name = "flox-activations"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
blake3.workspace = true
clap = { version = "4.5.20", default-features = false, features = ["std","usage", "help", "error-context", "derive"] }
clap_derive.workspace = true
env_logger = { version = "0.11.5", default-features = false }
flox-core.workspace = true
fslock.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
uuid.workspace = true
xdg.workspace = true
indoc.workspace = true


[dev-dependencies]
tempfile.workspace = true
temp-env.workspace = true
