[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.2"
tag_format = "v$version"
version_files = ["./crates/flox/Cargo.toml:version"]
changelog_incremental = true
major_version_zero = true
annotated_tag = true
bump_message = "bump: $current_version â†’ $new_version"
pre_bump_hooks = [
  "cargo update -p flox", # allow network to access dependency patches
  "nix flake update",
]
