[workspace]
members = ["crates/*"]

default-members = ["crates/flox"]

[patch.crates-io]
bpaf = { git = "https://github.com/ysndr/bpaf", branch = "error/more-suggestions" }
runix = { git = "https://github.com/flox/runix", branch = "feature/impure-flakerefs" }
