# List packages you wish to install in your environment under
# the `[install]` table
## [install] 
## hello = {}
## nodejs = { version = "^16.4.2" } 

# Set your activation hook ( run when entering the environment )
# You can write this inline with the `script` field, or provide a
# relative path to a file using the `file` field.
[hook]
script = """
  echo "Welcome to your flox environment!";
"""
