[package]
name = "systemd"
version = "0.1.0"
edition = "2024"

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_with.workspace = true
thiserror.workspace = true

[dev-dependencies]
indoc.workspace = true
