[package]
name = "flox-types"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1"
pretty_assertions = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_with = "2.0.1"
thiserror = "1.0"
url = "2.3"

[features]
extra-tests = [ ]
