[package]
name = "nef-lock-catalog"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
url.workspace = true
serde_json.workspace = true
toml.workspace = true
serde.workspace = true
indexmap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
catalog-api-v1 = { path = "../catalog-api-v1" }
reqwest = { workspace = true }
tokio.workspace = true
pollster.workspace = true
